### ISSUE TITLE
Automate keeping Optimism forks up to date

### ISSUE THREAD

**Issue by jannikluhn** [shutter-network/rolling-shutter#217]
We have to fork Cannon and L2geth and modify their implementation slightly. We should try to keep these codebases up to date with their sources. Find a way to automatically integrate new changes from the source into our fork.

**Comment by ezdac** [comment]
We decided to do this manually - I added a more detailed workflow of how to update the repos:

https://github.com/shutter-network/txtypes/blob/main/README.md
