### ISSUE TITLE
Make collator push batches to sequencer

### ISSUE THREAD

**Issue by jannikluhn** [shutter-network/rolling-shutter#219]
whenever a batch is available and the decryption key has been generated, push it to L2geth for execution.

**Comment by ezdac** [comment]
#278 still uses an ethereum rpc client to push to `eth_sendRawTransaction` - why don't we re-use this method and why do we have to add an additional namespace? We could distinguish by transaction type and recover the signature in order to check who submitted the batch-transaction.

**Comment by ezdac** [comment]
superseded by #334
