### ISSUE TITLE
Don't rely on activation-block as unique identifier for Eon

### ISSUE THREAD

**Issue by ezdac** [shutter-network/rolling-shutter#238]
The Owner of the `KeypersConfigsList` contract has the ability to set new keyper-set / activation-block combinations:
https://github.com/shutter-network/rolling-shutter/blob/51fc0fca60439d00888e61956601934d9214b69b/contracts/src/KeypersConfigsList.sol#L41-L49

## Problem

Although it is not allowed to set configs for lower `activation_block` than has been already set and for `activation_block` that lie in the past, it is possible to set an updated config for an **already existing `activation_block` that is still in the future, as long as no subsequent config has been set yet**.

However this ambiguity is not reflected in the emitted event:
https://github.com/shutter-network/rolling-shutter/blob/51fc0fca60439d00888e61956601934d9214b69b/contracts/src/KeypersConfigsList.sol#L65-L69

And is not directly retrievable by the getter function:
https://github.com/shutter-network/rolling-shutter/blob/51fc0fca60439d00888e61956601934d9214b69b/contracts/src/KeypersConfigsList.sol#L72-L76

While the getter function only returns the lastly appended config (thus the most recent that should be considered),
a client that only tracks chain-state by listening to events has to keep track of an append-order by themselves.

Also there could be one attack-vector for replay attacks when Keypers sign the PublicKeys in order to "prove" the validity of that key by majority vote:
- Keyper-set is `[keyper1, keyper2, keyper3]`
- all keypers sign the publickey and broadcast it as `EonPublicKey(activation_block=42, pubkey=0xdeadbeef, keyper-index=i)` for all indicides i
- now the keyper-set for `activation_block=42` is changed to `[keyper1, keyper2]`
- both keypers commit to an publikey,sign and broadcast it as `EonPublicKey(activation_block=42, pubkey=0xdecafbad, keyper-index=i)` for all indicices i
 - `keyper3` choses to re-broadcast all signed `EonPublicKey(activation_block=42, pubkey=0xdeadbeef)` messages

Since the ordering of the keyper-set did not change, the old signed messages with `pubkey=0xdeadbeef` would be still valid in the new keyper set and would have the same number of validly signed messages as `pubkey=0xdecafbad`.
This does not change that valid keypers would reject to use secretkeys associated with `pubkey=0xdeadbeef`,
but it does attack the publickey verification system.

## Proposal
We should get rid of the ambiguity allowing `(activation_block, event_index)` being non-unique.

We could reference the configs strictly by index:
``` solidity
function getConfig(uint64 index)
        public
        view
        returns (KeypersConfig memory)
    {
         // plus additional out-of-bounds check
          return keypersConfigs[index];
    }
 ```
 
 And also emit the index in the event
 ```solidity
        keypersConfigs.push(config);
        emit NewConfig({
            activationBlockNumber: config.activationBlockNumber,
            keyperSetIndex: config.setIndex,
            keyperConfigIndex: uint64(keypersConfigs.length) - 1;,
            threshold: config.threshold
        });
```

Then the keypers have to sign pubkey messages like `EonPublicKey(pubkey=0xdeadbeef, keyperConfigIndex=22, keyperIndex=1)` to make them unambiguously verifiable against the blockchain state.

Note, that `keyperConfigIndex` is not the same as the `keyperSetIndex` (formerly just `index`) , although the keyper-set index is sometimes named `ConfigIndex` or `EventIndex` in the rolling shutter code

**Comment by schmir-at-bb** [comment]
The following is the status after #275 is merged:

## Replay attack

The replay attack is not possible anymore, because the keypers now sign the following (which contains the eon and keyper config index)

https://github.com/shutter-network/rolling-shutter/blob/84cec66c8a1cb3707e616e3a0f114ad561e85f9a/rolling-shutter/shmsg/gossip.proto#L27-L38

## no getter function
I didn't change the contracts yet, we have no getter function that returns a KeypersConfig by index. For convenience we may add one, but we do not even call `getActiveConfig` from our go code.

**Comment by schmir-at-bb** [comment]
I failed to phrase the last point as a question. Should we add the getter function? Otherwise I'd say this issue can be closed.

**Comment by ezdac** [comment]
In general we need this functionality latest when we write the user-side code (Javascript lib). 
IIRC the go abigen generates getter functions for arrays automatically - if that's the case for the tool generating JS bindings as well we don't even need one in the code explicitly.

**Comment by schmir-at-bb** [comment]
ah right, thanks, it's public. so , solidity generates a getter function. I'm closing this one then.
