### ISSUE TITLE
Reevaluate EpochID encoding

### ISSUE THREAD

**Issue by ezdac** [shutter-network/rolling-shutter#269]
Following up on https://github.com/shutter-network/rolling-shutter/pull/239 @jannikluhn and I had the discussion whether 
the `<uint32 block_number><uint32 batch index>` coding of the EpochID is necessary.
We think that the EpochID can be any arbitrary number decided upon by the collator, as long as they stay unique (no reuse).
We did not see disadvantages to simply set the `EpochID` as the L2 `BatchIndex`, but thought this makes things easier.

Any objections? Why was the block number encoded in the epoch-id?

**Comment by jannikluhn** [comment]
Done in 291.
