### ISSUE TITLE
Add signed L1 Block number field  to `Shutter Tx`

### ISSUE THREAD

**Issue by ezdac** [shutter-network/rolling-shutter#270]
Currently the user only signs the `BatchIndex` in the `ShutterTx`, and the collator later decides on the `L1BlockNumber` to be included in the envelope BatchTx. The sequencer checks that the L1BlockNumber is within reasonable bounds with the current L1 block.

### Problem
This is problematic, since the collator could lie about the L1 block number (within the sequencer's bounds) to e.g. force usage 
of an older keyper-set.
Users would have encrypted transactions to the newer keyper set's public key, while the sequencer will decrypt with an older key.
This will render all user's transactions for that batch invalid.

### Solution
The collator returns the batch index **and** the L1 block he wants to use for the BatchTx to the user.
The user checks wether this is wihin bounds with current L1 state, and includes that block number in the signed Tx.

That way, the sequencer (or later maybe "slashers") can verify that `ShutterTx.L1Block == BatchIndex.L1Block`

**Comment by jannikluhn** [comment]
Types are updated in the following already merged PRs:

- https://github.com/shutter-network/go-ethereum/pull/3
- https://github.com/shutter-network/txtypes/pull/1 (tagged as v0.0.4)
- https://github.com/shutter-network/cannon/pull/8
- https://github.com/shutter-network/rolling-shutter/pull/293

Related, here's the PR that checks the l1 block number in cannon (waiting for review):

- https://github.com/shutter-network/cannon/pull/9

We don't check the l1 block number in the tx pool logic in the collator yet, see https://github.com/shutter-network/rolling-shutter/issues/290.

**Comment by ezdac** [comment]
There is one problem with this approach:
since the user has to commit to a specific L1 block number that matches the one from the collator, this has to be communicated in advance from collator to user (as stated above).
But we also allow to submit ShutterTx for some period in the future.
How can there be deterministic certainty about the L1blocknumber of say the next 5 batches?
Should the collator extrapolate l1blocknumbers based on epoch-time / l1-block time and publish the `(l1blocknumber, epoch-id)` data for the next 5 batches to the users? A possible deviation is then good enough for the sequencer since it still lies within bounds?

**Comment by jannikluhn** [comment]
Yeah, that's true. To some extent this has been the case already before because we used to encode the block number in the epoch id.

> Should the collator extrapolate l1blocknumbers based on epoch-time / l1-block time and publish the (l1blocknumber, epoch-id) data for the next 5 batches to the users? A possible deviation is then good enough for the sequencer since it still lies within bounds?

Yeah, I think that's fine. The extrapolation should be accurate enough, especially after the merge when we get constant block times.
