### ISSUE TITLE
Fix batch tx copying

### ISSUE THREAD

**Issue by jannikluhn** [shutter-network/rolling-shutter#274]
See https://github.com/shutter-network/go-ethereum/pull/1

After merging the fix, copy it to txtypes and Cannon using the shtypecopy tool.

**Comment by ezdac** [comment]
Txtypes has been update already by me

**Comment by jannikluhn** [comment]
If I'm not missing anything, it's done then. It's in [our go-ethereum fork](https://github.com/shutter-network/go-ethereum/blob/a495080a66b6606ddcbafae25dd2c8683fd3f552/core/types/batch_tx.go), [cannon](https://github.com/shutter-network/cannon/blob/3ad8b759ee57cd46551857bf36df6cc3ca968ba5/minigeth/core/types/batch_tx.go), and [txtypes](https://github.com/shutter-network/txtypes/blob/7db53eba23f0fc657eb8adb986a3e8ce50e092ce/types/batch_tx.go).
