### ISSUE TITLE
Move shcryptowasm from shutter to rolling shutter repo

### ISSUE THREAD

**Issue by jannikluhn** [shutter-network/rolling-shutter#276]
shcryptowasm currently lives in the "old" shutter repo that also contains shcrypto. We want to move it here so that it's closer to the snapshot shutter implementation which will use it the most for now.

Unfortunately, simply moving it fails:

```
$ make shcryptowasm
tinygo build -target wasm -size full -o ./bin/encrypt.wasm ./shcryptowasm/encrypt_wasm.go
# github.com/ethereum/go-ethereum/common
../../../../go/pkg/mod/github.com/ethereum/go-ethereum@v1.10.16/common/debug.go:35:8: PrintStack not declared by package debug
make: *** [Makefile:13: shcryptowasm] Error 
```

I presume this is because either the updated Go version (1.17 -> 1.18) or the updated go-ethereum (1.10.8 -> 1.10.16).

Potential fixes might be to strip shcrypto and thus shcryptowasm of it's go-ethereum dependency (we mostly use the `bn256` library which could import directly) which might have the nice sideeffect of reduced binary size. We could also decide to just leave it in the old Repo.

**Comment by schmir-at-bb** [comment]
https://github.com/shutter-network/rolling-shutter/pull/277 implements this

**Comment by schmir-at-bb** [comment]
done in 8520542b23909ba79ec11720e364f64083679938
