### ISSUE TITLE
Collator `eth_sendRawTransaction`: error delegation in compliance with JSON-RPC

### ISSUE THREAD

**Issue by ezdac** [shutter-network/rolling-shutter#282]
We don't comply to the ethereum JSON-RPC response format with a structured error json.
Also, there currently is no mechanism to distinguish between internal errors (which shouldn't be completely user exposed) and errors that should be communicated to the user.
Both requirements call for some form of wrapped errors, that can be dispatched and marshalled in the outer http-handling layer later on.

**Comment by jannikluhn** [comment]
closing because not a priority
