### ISSUE TITLE
Collator batch handler: database cleanup of txs after batch-inclusion

### ISSUE THREAD

**Issue by ezdac** [shutter-network/rolling-shutter#283]
Currently all transactions that can be unmarshalled will be persisted to the database, and there is no purging mechanism in place. Transactions do not need to be kept forever, and can be deleted after they have been confirmed on-chain or their epoch expired. This means we currently have a cause of unnecessary, unlimited database bloat.

**Comment by jannikluhn** [comment]
not relevant because we ended up not storing transactions in the db
