### ISSUE TITLE
Collator batch handler: synchronize epoch start with latest batch inclusion

### ISSUE THREAD

**Issue by ezdac** [shutter-network/rolling-shutter#286]
Currently a thread in the collator will continuously trigger the start of new epochs with a time ticker every X seconds.
That interval should only be the minimum time between epochs though:

We need to wait on the successful inclusion of the previous epoch in the l2 chain state before we can validate and include transactions for the next batch. This is because the validation of pending transactions depends on the state-changes caused by the previous batches' decrypted transactions.

Starting a new epoch is dependent on the validated pending batches' transactions (for the Decryption trigger), so we should initiate sending the  trigger only when:
1) the ticker time interval since the last epoch start was reached
2) **AND** the previous batch-transaction has been successfully sent, confirmed and is included in the latest state of the l2 chain

**Comment by jannikluhn** [comment]
not concretely relevant because refactoring
