### ISSUE TITLE
 Mock sequencer: query L1 block-number from JSON-RPC node

### ISSUE THREAD

**Issue by ezdac** [shutter-network/rolling-shutter#324]
The collator will  fetch the current `L1BlockNumber` from a layer 1 Ethereum node in order to include this in the signed in the `BatchTx`.
In practice, the sequencer will also have to query this value and only allow a BatchTx that is (within reasonable bounds) close to the sequencers view on the l1 chain.

This should also be fetched and checked in the mock-sequencer.

**Comment by jannikluhn** [comment]
see also https://github.com/shutter-network/rolling-shutter/issues/271
