### ISSUE TITLE
Collator: initiate `shutter_submitBatch` on new decryption-keys

### ISSUE THREAD

**Issue by ezdac** [shutter-network/rolling-shutter#334]
A parallel process has to constanly check for new values of `cltrdb.decryption_key` (see #333 ).
Whenever there is a new key that corresponds with the last closed batch, the process has to:
- retrieve all committed on shutter-transactions from the DB for that epoch
- construct a new `BatchTx` including the rlp-encoded shutter-transactions, the determined l1-block-number (see #336 ), decryption key and additional metadata :
   ```go
   type BatchTx struct {
	   ChainID       *big.Int
	   DecryptionKey []byte
	   BatchIndex    uint64
	   L1BlockNumber uint64
	   Timestamp     *big.Int
	   Transactions  [][]byte
   }
   ```
- submit the RLP encoded and signed `BatchTx` to the `shutter_submitBatch` JSON RPC endpoint at the sequencer
- eventually listen on the `shutter_batchIndex` endpoint to wait for successful submission of the batch

**Comment by ezdac** [comment]
#331 might be relevant for this, since this implements the server-side `shutter_submitBatch` method

**Comment by schmir-at-bb** [comment]
Implemented in `collator/batchsubmission.go`
