### ISSUE TITLE
Investigate key generation performance

### ISSUE THREAD

**Issue by jannikluhn** [shutter-network/rolling-shutter#452]
During key generation, the following steps might take a non-negligible amount of time:

- event syncing from the chain
- computing the decryption key share
- broadcasting decryption key share
- validating decryption key shares
- aggregating shares to get the decryption keys
- broadcasting decryption keys
- validating decryption keys

We should investigate how much time each of those steps take when there's few or many keys to produce. We should also check if there's potentially other steps missing in this list. As a result, we will know where to look for optimization potential.

**Comment by konradkonrad** [comment]
```
go test -bench=. ./medley/testkeygen -cpuprofile profile.out
goos: linux
goarch: amd64
pkg: github.com/shutter-network/rolling-shutter/rolling-shutter/medley/testkeygen
cpu: Intel(R) Core(TM) i5-8350U CPU @ 1.70GHz
BenchmarkKeyperComputeSecretShares-8   	      22	  52727480 ns/op
BenchmarkSecretKeyGeneration-8         	      33	  36374355 ns/op
BenchmarkFullBlock-8                   	       2	 815570668 ns/op
PASS
ok  	github.com/shutter-network/rolling-shutter/rolling-shutter/medley/testkeygen	116.344s
```

![flame](https://github.com/shutter-network/rolling-shutter/assets/3705643/2ad07c22-a592-4188-b73b-2d4e049e4119)
