### ISSUE TITLE
Bootstrap script stopped working

### ISSUE THREAD

**Issue by jannikluhn** [shutter-network/rolling-shutter#489]
The error I'm getting is "not allowed to send" when submitting the batch config. This is surprising because the bootstrap keyper should be allowed to send.

Adding the following line [here](https://github.com/shutter-network/rolling-shutter/blob/ad4495e0dc95effa0c8256ccc09592d779a53d97/rolling-shutter/keyperimpl/optimism/bootstrap/bootstrap.go#L36) fixes it, but I'm not sure why it's not working automatically:

```go
ms.AllowedToSend.Store(true)
```

**Comment by konradkonrad** [comment]
Hmm. So we [allow send reactively](https://github.com/shutter-network/rolling-shutter/blob/9559aaae50a451a270727715a975431f3ed468a8/rolling-shutter/keyper/keyper.go#L383-L396), if we found a batch config, that contains our keyper's address.

For the original issue that sounds like a reasonable approach.

For the bootstrap keyper, I think it is reasonable to manually override in the way you did it.

**Comment by konradkonrad** [comment]
Closed by https://github.com/shutter-network/rolling-shutter/pull/509
