### ISSUE TITLE
tx-pointer gets overridden by any key(share) message

### ISSUE THREAD

**Issue by fredo** [shutter-network/rolling-shutter#498]
@konradkonrad please post your observations

**Comment by konradkonrad** [comment]
I was mistaken:

It looked as if a rogue keyper could arbitrarily change other keyper's tx-pointers:

https://github.com/shutter-network/rolling-shutter/blob/f21a5db5b27894dddc384d975418397c8858832e/rolling-shutter/keyperimpl/gnosis/handlers.go#L295-L315

as long as the message validates for the receivers.

However, the prerequisites for validation are:
- [valid message layout](https://github.com/shutter-network/rolling-shutter/blob/f21a5db5b27894dddc384d975418397c8858832e/rolling-shutter/keyperimpl/gnosis/handlers.go#L201-L221)
- [valid signatures of at least threshold validators](https://github.com/shutter-network/rolling-shutter/blob/f21a5db5b27894dddc384d975418397c8858832e/rolling-shutter/keyperimpl/gnosis/handlers.go#L228-L230)

So this is "threshold safe", as far as I understand!

The `tx-pointer` value that will be updated by a `DecryptionKeys` message, is being [voted upon during `KeyShares` gossiping](https://github.com/shutter-network/rolling-shutter/blob/f21a5db5b27894dddc384d975418397c8858832e/rolling-shutter/keyperimpl/gnosis/handlers.go#L105-L115).
