### ISSUE TITLE
[EPIC] Create public Shutter Gnosis Chain dashboard

### ISSUE THREAD

**Issue by pepae** [shutter-network/rolling-shutter#503]
- [x] Define/spec dashboard in a meeting @faheelsattar @fredo @ulope @pepae 
- [ ] Build it on top of observer
- [ ] Deploy

**Comment by pepae** [comment]
We had a meeting and starting to spec the requirements for this

The end goal is a public dashboard with 2 tabs, 1) Global view, 2) Inspect Individual transaction 

This can serve as inspiration for a subset of the data presented: https://x.com/drakefjustin/status/1801321889152835758/video/1

# Rough requirements:

## Global view

### Transactions and Timing
1. **List of Transactions**
   - **Seen in Encrypted Mempool**: Timestamp of each transaction.
   - **Keys Released**: Slot number for each transaction.

2. **Decryption Keys**
   - **Timestamps Seen**: List of timestamps when decryption keys were observed.

### Inclusion and Execution
3. **Transaction Inclusion Analysis**
   - **Number of Slots/Transactions Not Included as Expected**: Count of slots/transactions that failed to be included.
   - **Successfully Executed Transactions**: Total number following the shutter protocol correctly.
   - **Failed Transactions**: Total number that were not included as expected.

### Validator and Keyper Statistics
4. **Validator Statistics**
   - **Number of Shutterized Validators**: Total number and percentage of all validators.
   - **Encrypted Validators**: Percentage of validators using encryption.

5. **Keyper Statistics**
   - **Number of Keypers**: Count of online keypers.
   - **Keyper Threshold**: Threshold number of keypers required for operation.

### Transaction Metrics
6. **Transaction Metrics**
   - **Number of Encrypted RPCs**: Total count of encrypted remote procedure calls.
   - **Number of Encrypted Transactions**: Total count of encrypted transactions.
   - **Percentage of Encrypted Transactions**: Percentage of overall transactions that are encrypted.
   
### Inclusion Time Analysis
7. **Inclusion Time**
   - **Average Projected Inclusion Time**: Average expected time for transaction inclusion.
   - **Historical Inclusion Time**: Distribution and historical data of transaction inclusion times.

## Inspect Individual transaction

### Users looking up their own transaction:

8. encrypted tx -> was key released?/ when -> raw transaction -> (when) was it included in the block

**Comment by pepae** [comment]
@ulope will schedule a dev team meeting to further narrow down the specs and plan development.
Could you then also estimate the time line on the 2 milestones?

**Comment by fredo** [comment]
We had a meeting and starting to spec the requirements for this

The end goal is a public dashboard with 2 tabs, 1) Global view, 2) Inspect Individual transaction

This can serve as inspiration for a subset of the data presented: https://x.com/drakefjustin/status/1801321889152835758/video/1

# Rough requirements:
## Global view
### Transactions and Timing
1) List of Transactions
    * **Seen in Encrypted Mempool**: Timestamp of each transaction.
    * **Keys Released**: Slot number for each transaction.
 
2) Decryption Keys
    * **Timestamps Seen**: List of timestamps when decryption keys were observed
    
### Inclusion and Execution
3) Transaction Inclusion Analysis
    * **Number of Slots/Transactions Not Included as Expected**: Count of slots/transactions that failed to be included.
    * **Successfully Executed Transactions**: Total number following the shutter protocol correctly.
    * **Failed Transactions**: Total number that were not included as expected.

### Validator and Keyper Statistics
4) Validator Statistics
    * **Number of Shutterized Validators**: Total number and percentage of all validators.
    * **Encrypted Validators**: Percentage of validators using encryption.

5) Keyper Statistics
    * **Number of Keypers**: Count of online keypers.
    * **Keyper Threshold**: Threshold number of keypers required for operation.

### Transaction Metrics

6) Transaction Metrics
    * **Number of Encrypted RPCs**: Total count of encrypted remote procedure calls.
    * **Number of Encrypted Transactions**: Total count of encrypted transactions.
    * **Percentage of Encrypted Transactions**: Percentage of overall transactions that are encrypted.

### Inclusion Time Analysis
7) Inclusion Time
    * **Average Projected Inclusion Time**: Average expected time for transaction inclusion.
    * **Historical Inclusion Time**: Distribution and historical data of transaction inclusion times.

## Inspect Individual transaction
### Users looking up their own transaction:
8) encrypted tx -> was key released?/ when -> raw transaction -> (when) was it included in the block

**Comment by fredo** [comment]
closed in favour of https://github.com/shutter-network/shutter-explorer/issues/1
